### ISSUE TITLE
Index.yaml loses previous versions for private repositories

### ISSUE THREAD

**Issue by stephen-harris** [stecky/yet-another-chart-releaser#2]
**Describe the bug**
When publishing a new chart version, the previous chart version is effectively removed from index.yaml on the `gh-pages` branches.

**To Reproduce**
1. Configure yet-another-chart-releaser-action:
```
- name: Run chart-releaser
  uses: stecky/yet-another-chart-releaser-action@v1
  env:
    YACR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  with:
    charts_dir: chart
    packages_with_index: true
    charts_repo_url: https://raw.githubusercontent.com/<org>/<repo>/gh-pages
```
2. Create an initial release observe the `index.yaml` generated in `gh-pages` contains this version
3. Create a second release. Observe that while the `tgz` file of the previous version is still present, the version has been replaced in `index.yaml` with this second release

**Expected behavior**
I would expect to see the second version appended:

```
apiVersion: v1
entries:
  <chart>:
  - apiVersion: v2
    appVersion: 0.1.9
    created: "2021-05-21T15:20:56.683660178Z"
    description: <description>
    digest: cea83d5b4f6cf7a780c8aec185b221ef0aac791daa43b768c801573b97f395f6
    name: <chart>
    type: application
    urls:
    - <chart>-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v2
    appVersion: 0.2.0
    created: "2021-05-21T15:20:56.683660178Z"
    description: <description>
    digest: 141f0d9770883ad2ba4687e775bf74002ce89fdf605569021662d0aefd146f3f
    name: <chart>
    type: application
    urls:
    - <chart>-0.2.0.tgz
    version: 0.2.0
generated: "2021-05-21T15:23:26.683673678Z"
```

**Additional context**

I believe this is due to the fact that this call will return 404 due to lack of credentials: https://github.com/stecky/yet-another-chart-releaser/blob/c5b06f45c3c52f4bd6a4b4b562627252c61e4ce2/pkg/releaser/.go#L112. Consequently, this branch of the `if` statement is executed: https://github.com/stecky/yet-another-chart-releaser/blob/c5b06f45c3c52f4bd6a4b4b562627252c61e4ce2/pkg/releaser/releaser.go#L137 - i.e. a new empty index file is created, and the previous version is effectively lost.

This confirmed by the output of the GitHub action:

```
Run stecky/yet-another-chart-releaser-action@v1
Looking up latest tag...
Discovering changed charts since '<chart>-0.1.9'...
Installing yacr v0.3.3...
Adding yacr directory to PATH...
Packaging chart 'chart/jaws-journey'...
Successfully packaged chart in /home/runner/work/<chart>/<chart>/chart/jaws-journey and saved it to: .yacr-release-packages/<chart>-0.2.0.tgz
Releasing charts...
Preparing worktree (detached HEAD 4b43f26)
HEAD is now at 4b43f26 Update index.yaml
[detached HEAD dac0609] Publishing chart package for <chart>-0.2.0
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 <chart>-0.2.0.tgz
Pushing to branch "gh-pages"
To https://github.com/<org>/<chart>
   4b43f26..dac0609  HEAD -> gh-pages
From https://github.com/<org>/<chart>
   4b43f26..dac0609  gh-pages   -> origin/gh-pages
 * [new tag]         <chart>-0.2.0 -> <chart>-0.2.0
Executing command git [push ***github.com/<org>/<chart> HEAD:refs/heads/gh-pages]Updating charts repo index...
UpdateIndexFile new index at .yacr-index/index.yaml
Found <chart>-0.2.0.tgz
Extracting chart metadata from .yacr-release-packages/<chart>-0.2.0.tgz
Calculating Hash for .yacr-release-packages/<chart>-0.2.0.tgz
Updating index .yacr-index/index.yaml
Preparing worktree (detached HEAD dac0609)
HEAD is now at dac0609 Publishing chart package for <chart>-0.2.0
[detached HEAD de60b35] Update index.yaml
 1 file changed, 6 insertions(+), 6 deletions(-)
Pushing to branch "gh-pages"
To https://github.com/<org>/<chart>
   dac0609..de60b35  HEAD -> gh-pages
Executing command git [push ***github.com/<org>/<chart> HEAD:refs/heads/gh-pages]
```

**Possible solution**

Rather than  trying to GET the index.yaml file directly, we could  use `git.AddWorktree` to checkout a the branch, and use the existing index.yaml file on that branch. However, I'm not sure if there's a use-case that you'd like to support that would prohibit that. If that does seem a reasonable solution, I'd be happy to provide a PR.
